# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculatePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calculatePage(object):
    def setupUi(self, calculatePage):
        calculatePage.setObjectName("calculatePage")
        calculatePage.resize(413, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(calculatePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit = QtWidgets.QDateEdit(calculatePage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(calculatePage)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(calculatePage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(calculatePage)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.submit = QtWidgets.QPushButton(calculatePage)
        self.submit.setObjectName("submit")
        self.verticalLayout.addWidget(self.submit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(calculatePage)
        QtCore.QMetaObject.connectSlotsByName(calculatePage)

    def retranslateUi(self, calculatePage):
        _translate = QtCore.QCoreApplication.translate
        calculatePage.setWindowTitle(_translate("calculatePage", "CalculatePage"))
        self.label.setText(_translate("calculatePage", "Start Date"))
        self.label_2.setText(_translate("calculatePage", "End Date"))
        self.submit.setText(_translate("calculatePage", "Show Results"))
