# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IgnoredIngredientsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ignoredIngredientsPage(object):
    def setupUi(self, ignoredIngredientsPage):
        ignoredIngredientsPage.setObjectName("ignoredIngredientsPage")
        ignoredIngredientsPage.resize(255, 133)
        self.verticalLayout = QtWidgets.QVBoxLayout(ignoredIngredientsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ignoredIngredientsPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(ignoredIngredientsPage)
        self.label_2.setToolTip("")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.scrollArea = QtWidgets.QScrollArea(ignoredIngredientsPage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 235, 56))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(ignoredIngredientsPage)
        QtCore.QMetaObject.connectSlotsByName(ignoredIngredientsPage)

    def retranslateUi(self, ignoredIngredientsPage):
        _translate = QtCore.QCoreApplication.translate
        ignoredIngredientsPage.setWindowTitle(_translate("ignoredIngredientsPage", "IgnoredIngredientsPage"))
        self.label.setText(_translate("ignoredIngredientsPage", "Ignored Ingredients"))
        self.label_2.setText(_translate("ignoredIngredientsPage", "These are ingredients that you know are not causing any of your symptoms."))
