# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItemInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_itemInput(object):
    def setupUi(self, itemInput):
        itemInput.setObjectName("itemInput")
        itemInput.resize(327, 63)
        self.horizontalLayout = QtWidgets.QHBoxLayout(itemInput)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input = QtWidgets.QLineEdit(itemInput)
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.deleteBtn = QtWidgets.QPushButton(itemInput)
        self.deleteBtn.setStyleSheet("color: #fff; background-color: #f00; padding: 5px 10px;")
        self.deleteBtn.setObjectName("deleteBtn")
        self.horizontalLayout.addWidget(self.deleteBtn)

        self.retranslateUi(itemInput)
        QtCore.QMetaObject.connectSlotsByName(itemInput)

    def retranslateUi(self, itemInput):
        _translate = QtCore.QCoreApplication.translate
        itemInput.setWindowTitle(_translate("itemInput", "ItemInput"))
        self.deleteBtn.setText(_translate("itemInput", "Delete"))
