# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultListing.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_resultListing(object):
    def setupUi(self, resultListing):
        resultListing.setObjectName("resultListing")
        resultListing.resize(375, 123)
        self.mainLayout = QtWidgets.QVBoxLayout(resultListing)
        self.mainLayout.setObjectName("mainLayout")
        self.symptomLabel = QtWidgets.QLabel(resultListing)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.symptomLabel.setFont(font)
        self.symptomLabel.setObjectName("symptomLabel")
        self.mainLayout.addWidget(self.symptomLabel)
        self.ingredientsLayout = QtWidgets.QFormLayout()
        self.ingredientsLayout.setObjectName("ingredientsLayout")
        self.timeLabel1 = QtWidgets.QLabel(resultListing)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel1.setFont(font)
        self.timeLabel1.setObjectName("timeLabel1")
        self.ingredientsLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.timeLabel1)
        self.timeLabel2 = QtWidgets.QLabel(resultListing)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel2.setFont(font)
        self.timeLabel2.setObjectName("timeLabel2")
        self.ingredientsLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.timeLabel2)
        self.timeLabel3 = QtWidgets.QLabel(resultListing)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel3.setFont(font)
        self.timeLabel3.setObjectName("timeLabel3")
        self.ingredientsLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.timeLabel3)
        self.ingredientsLabel1 = QtWidgets.QLabel(resultListing)
        self.ingredientsLabel1.setStyleSheet("background-color: #ddd; padding: 2px 5px;")
        self.ingredientsLabel1.setWordWrap(True)
        self.ingredientsLabel1.setObjectName("ingredientsLabel1")
        self.ingredientsLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ingredientsLabel1)
        self.ingredientsLabel2 = QtWidgets.QLabel(resultListing)
        self.ingredientsLabel2.setStyleSheet("background-color: #ddd; padding: 2px 5px;")
        self.ingredientsLabel2.setWordWrap(True)
        self.ingredientsLabel2.setObjectName("ingredientsLabel2")
        self.ingredientsLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ingredientsLabel2)
        self.ingredientsLabel3 = QtWidgets.QLabel(resultListing)
        self.ingredientsLabel3.setStyleSheet("background-color: #ddd; padding: 2px 5px;")
        self.ingredientsLabel3.setWordWrap(True)
        self.ingredientsLabel3.setObjectName("ingredientsLabel3")
        self.ingredientsLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ingredientsLabel3)
        self.mainLayout.addLayout(self.ingredientsLayout)
        self.mainLayout.setStretch(1, 1)

        self.retranslateUi(resultListing)
        QtCore.QMetaObject.connectSlotsByName(resultListing)

    def retranslateUi(self, resultListing):
        _translate = QtCore.QCoreApplication.translate
        resultListing.setWindowTitle(_translate("resultListing", "ResultListing"))
        self.symptomLabel.setText(_translate("resultListing", "Symptom"))
        self.timeLabel1.setText(_translate("resultListing", "timeLabel1"))
        self.timeLabel2.setText(_translate("resultListing", "timeLabel2"))
        self.timeLabel3.setText(_translate("resultListing", "timeLabel3"))
        self.ingredientsLabel1.setText(_translate("resultListing", "Ingredients"))
        self.ingredientsLabel2.setText(_translate("resultListing", "Ingredients"))
        self.ingredientsLabel3.setText(_translate("resultListing", "Ingredients"))
