# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_resultsPage(object):
    def setupUi(self, resultsPage):
        resultsPage.setObjectName("resultsPage")
        resultsPage.resize(348, 300)
        self.mainLayout = QtWidgets.QVBoxLayout(resultsPage)
        self.mainLayout.setObjectName("mainLayout")
        self.label = QtWidgets.QLabel(resultsPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.mainLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(resultsPage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 328, 122))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainLayout.addWidget(self.scrollArea)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem)

        self.retranslateUi(resultsPage)
        QtCore.QMetaObject.connectSlotsByName(resultsPage)

    def retranslateUi(self, resultsPage):
        _translate = QtCore.QCoreApplication.translate
        resultsPage.setWindowTitle(_translate("resultsPage", "ResultsPage"))
        self.label.setText(_translate("resultsPage", "Results"))
